# Generated by Django 3.1.4 on 2021-01-01 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Nazwa')),
                ('address', models.TextField(verbose_name='Adres')),
                ('delivery_address', models.TextField(verbose_name='Adres dostawy')),
                ('nip', models.CharField(help_text='Wprowadź 10 liczb w ciągu', max_length=10, unique=True, verbose_name='NIP')),
                ('industy', models.CharField(choices=[('BHP', 'BHP'), ('SPA', 'SPAWALNICTWO'), ('SZL', 'SZLIFIERSTWO'), ('AUT', 'AUTOMATYKA PRZEMYSŁOWA'), ('HAN', 'HANDEL PRZEMYSŁOWY'), ('BUD', 'BUDOWNICTWO')], max_length=3, null=True, verbose_name='Branża')),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Nazwa pozycji')),
                ('index', models.PositiveIntegerField(unique=True, verbose_name='Indeks')),
                ('description', models.TextField(null=True, verbose_name='Opis szczegółowy')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Kontroluj ilość systemową ze stanem fizycznym!', verbose_name='Ilość na stanie magazynowym')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Nazwa')),
                ('address', models.TextField(verbose_name='Adres')),
                ('nip', models.CharField(help_text='Wprowadź 10 liczb w ciągu', max_length=10, unique=True, verbose_name='NIP')),
                ('industy', models.CharField(choices=[('BHP', 'BHP'), ('SPA', 'SPAWALNICTWO'), ('SZL', 'SZLIFIERSTWO'), ('AUT', 'AUTOMATYKA PRZEMYSŁOWA')], max_length=3, null=True, verbose_name='Branża')),
            ],
        ),
        migrations.CreateModel(
            name='WorkStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Nazwa stanowiska pracy')),
                ('norm', models.PositiveIntegerField(verbose_name='Dzienna norma produkcyjna')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Nazwa pozycji')),
                ('index', models.PositiveIntegerField(unique=True, verbose_name='Indeks')),
                ('description', models.TextField(null=True, verbose_name='Opis szczegółowy')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Kontroluj ilość systemową ze stanem fizycznym!', verbose_name='Ilość na stanie magazynowym')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.supplier', verbose_name='Dostawca')),
            ],
        ),
        migrations.CreateModel(
            name='GoodMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needed', models.PositiveIntegerField(default=1, verbose_name='Potrzeba')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.good', verbose_name='Produkt')),
                ('material', models.ForeignKey(on_delete=models.SET('Element usunięto'), to='project.material', verbose_name='Element')),
            ],
        ),
        migrations.AddField(
            model_name='good',
            name='material',
            field=models.ManyToManyField(through='project.GoodMaterial', to='project.Material'),
        ),
        migrations.CreateModel(
            name='DocumentSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=12, unique=True, verbose_name='Numer dokumentu')),
                ('destination', models.CharField(max_length=24, verbose_name='Przeznaczenie')),
                ('materials', models.ManyToManyField(to='project.Material', verbose_name='Pozycje na dokumencie')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.supplier', verbose_name='Dostawca')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=12, unique=True, verbose_name='Numer dokumentu')),
                ('destination', models.CharField(max_length=24, verbose_name='Przeznaczenie')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.customer', verbose_name='Dostawca')),
                ('good', models.ManyToManyField(to='project.Good', verbose_name='Pozycje na dokumencie')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nazwa rabatu')),
                ('value_percent', models.PositiveIntegerField(help_text='Ustalona wartość z dostawcą', verbose_name='Wartość procentowa')),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.supplier', verbose_name='Rabat dla dostawcy')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nazwa rabatu')),
                ('value_percent', models.PositiveIntegerField(help_text='Nie powinna przekraczać 35', verbose_name='Wartość procentowa')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.customer', verbose_name='Rabat dla klienta')),
            ],
        ),
    ]
