# Generated by Django 3.1.4 on 2021-01-03 13:05

from django.db import migrations, models
import project.validators


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='nip',
            field=models.CharField(help_text='Wprowadź 10 liczb w ciągu', max_length=10, unique=True, validators=[project.validators.validate_len_nip, project.validators.validate_symbols_nip], verbose_name='NIP'),
        ),
        migrations.AlterField(
            model_name='discountcustomer',
            name='value_percent',
            field=models.PositiveIntegerField(help_text='Nie powinna przekraczać 35', validators=[project.validators.validate_value_discount], verbose_name='Wartość procentowa'),
        ),
        migrations.AlterField(
            model_name='discountsupplier',
            name='value_percent',
            field=models.PositiveIntegerField(help_text='Ustalona wartość z dostawcą', validators=[project.validators.validate_value_discount], verbose_name='Wartość procentowa'),
        ),
        migrations.AlterField(
            model_name='material',
            name='index',
            field=models.PositiveIntegerField(unique=True, validators=[project.validators.validate_len_index], verbose_name='Indeks'),
        ),
        migrations.AlterField(
            model_name='material',
            name='quantity',
            field=models.PositiveBigIntegerField(default=0, help_text='Kontroluj ilość systemową ze stanem fizycznym!', verbose_name='Ilość na stanie magazynowym'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='nip',
            field=models.CharField(help_text='Wprowadź 10 liczb w ciągu', max_length=10, unique=True, validators=[project.validators.validate_len_nip, project.validators.validate_symbols_nip], verbose_name='NIP'),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='norm',
            field=models.PositiveIntegerField(validators=[project.validators.validate_norm], verbose_name='Dzienna norma produkcyjna'),
        ),
    ]
