# Generated by Django 3.1.4 on 2021-01-03 13:07

from django.db import migrations, models
import project.validators


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20210103_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='index',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='Indeks'),
        ),
        migrations.AlterField(
            model_name='good',
            name='quantity',
            field=models.PositiveBigIntegerField(default=0, help_text='Kontroluj ilość systemową ze stanem fizycznym!', verbose_name='Ilość na stanie magazynowym'),
        ),
        migrations.AlterField(
            model_name='material',
            name='index',
            field=models.PositiveBigIntegerField(unique=True, validators=[project.validators.validate_len_index], verbose_name='Indeks'),
        ),
    ]
