# Generated by Django 3.1.4 on 2021-01-03 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20210103_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentcustomer',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.customer', verbose_name='Klient'),
        ),
        migrations.AlterField(
            model_name='goodmaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.material', verbose_name='Element'),
        ),
    ]
