# Generated by Django 3.1.4 on 2021-01-08 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20210103_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentcustomer',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='project.customer', verbose_name='Klient'),
        ),
        migrations.AlterField(
            model_name='documentsupplier',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='project.supplier', verbose_name='Dostawca'),
        ),
        migrations.AlterField(
            model_name='material',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='project.supplier', verbose_name='Dostawca'),
        ),
    ]
